.TH SAFER 1
.SH NAME
safer \- run project tools in containers using proxy scripts
.SH SYNOPSIS
.B safer
[-d SAFER_DIR]
.br
.B safer
[OPTIONS] <CMD> <IMAGE> [DIR...]
.br
.B safer
(-l|-i|-li) TOOL [DIR...]
.SH DESCRIPTION
.B safer
creates a CMD script to run a dev tool in the current directory using a
container IMAGE.
.P
The current directory, and any extra DIR specified, are mounted in the
container using the same paths.
.P
The scripts are created in the SAFER_DIR directory,
.B .safer
by default. You can run
.B safer
without any option to get a new definition for the
.B PATH
environment variable. You can also run
.B 'eval $(safer)'
to make the scripts available immediately.
.P
When used with
.B -l
and
.B -i
,
.B safer
uses TOOL definitions from its internal library.
.P
See
.B NOTES
for more details.
.SH OPTIONS
.TP
.BR \-e
Tool entrypoint in the image.
.TP
.BR \-p
Port to expose (e.g., 8080 or 80:8080).
.TP
.BR \-k
Run the tool in a persistent container.
.TP
.BR \-n
Use this name to persist the container (implies -k).
.TP
.BR \-d
Directory for the scripts.
.br
Default: .safer
.TP
.BR \-R
Runtime cli command. Override podman/docker detection.
.TP
.BR \-X
Runtime extra args.
.br
Docker default: --user "$(id -u):$(id -g)"
.TP
.BR \-K
Command used to persist the container (implies -k).
.br
Default: sleep inf
.TP
.BR \-S
Argument injected to stop persisting containers (implies -k).
.br
Default: --safer-stop
.TP
.BR \-f
Force script replacement.
.TP
.BR \-s
Skip container pseudo-tty allocation.
.TP
.BR \-l
Get the tool definition from the library.
.TP
.BR \-i
Install a Containerfile from the library.
.TP
.BR \-v
Display the current version.
.TP
.BR \-h
Display usage and exit.
.SH ENVIRONMENT
.TP
.BR SAFER_DIR
Directory for the scripts.
.br
Default: .safer
.TP
.BR SAFER_LIB_PATH
Directories for the library. See
.BR FILES.
.TP
.BR SAFER_RT_CMD
Runtime cli command. See
.BR NOTES.
.TP
.BR SAFER_RT_ARGS
Runtime extra args. See
.BR NOTES.
.TP
.BR SAFER_PERSIST_CMD
Command used to persist the container.
.br
Default: sleep inf
.TP
.BR SAFER_PERSIST_STOP_CMD
Argument injected to stop persisting containers.
.br
Default: --safer-stop
.SH FILES
.TP
.BR /etc/safer ", "~/.saferrc ", ".saferrc
These files are sourced by safer.
.TP
.BR ~/.local/share/safer ", "/usr/share/safer ", "/usr/local/share/safer
These are the default locations for the
.B tools
and
.B images
directories used by the library options.
.SH NOTES
.P
PERSISTENT CONTAINERS
.P
Instead of running a new container each time the CMD is called, you can
run
.BR safer
with
.BR -k .
If so, a named persistent container will be created by the script and
the commands will execute using
.BR exec,
preserving the state of the container across executions. This container
can be stopped using the CMD with the injected argument
.BR --safer-stop.
You can specify a name for the container with
.BR -n .
.P
RUNTIME DETECTION
.P
.B safer
will try to detect a container runtime. It will prefer
.B podman
over
.B docker.
.BR SAFER_RT_CMD
and
.BR SAFER_RT_ARGS
will override this detection.
.P
If
.B docker
is selected, '--user "$(id -u):$(id -g)"' will be used as the default
runtime arguments.
.P
PSEUDO-TTY ALLOCATION
.P
To ensure interactive tools can be used,
.BR safer
will instruct container runtimes to allocate a pseudo-tty by default.
Set the flag
.BR -s
to skip this when using LSPs and similar tools that are controlled by
another process using STDIN.
.SH CAVEATS
.P
PHYSICAL/ABSOLUTE PATHS
.P
.B safer
enforces absolute paths in scripts generation. This is coherent with
how container runtimes work but may break host tools if they need path
information from inside the container.
