#!/bin/sh

# TODO: auto-image from cmd name
# TODO: safer-images if not image

# Section 1: Init safer and read args/env

safer_ver=0.0-dev

safer_usage="Usage:
$0 [[OPTIONS] [<cmd> <image> [dir...]]]

Arguments:
 cmd         Name of the tool executable.
 image       Image where the tool executable resides.
 dir         Extra directories to mount in the container.

For the full list of Options and Environment Vars, see the man page.

Options:
 -e             Tool entrypoint in the image.
 -p             Port to expose (e.g., 8080 or 80:8080).
 -k             Use this name to persist the container.
 -d             Directory for the scripts. Default: .safer .
 -v, --version  Display the current version.
 -h, --help     Display usage and exit.

Environment Vars:
 SAFER_DIR      Directory for the scripts. Default .safer .

Config files: /etc/safer, ~/.saferrc, .saferrc"

[ -e "/etc/safer" ] && . "/etc/safer"
[ -e "$HOME/.saferrc" ] && . "$HOME/.saferrc"
[ -e ".saferrc" ] && . ".saferrc"

safer_dir=${SAFER_DIR:-.safer}

if [ "$#" -eq 0 ]; then
	case ":$PATH:" in
		*":$safer_dir:"*) exit ;;
		*) PATH="$(realpath "$safer_dir"):$PATH" ${SHELL:-sh}; exit ;;
	esac
fi

case " $@ " in
	*" -v "*|*" --version "*) echo $safer_ver && exit ;;
	*" -h "*|*" --help "*) echo "$safer_usage" && exit ;;
esac

safer_cmd=
safer_image=
safer_entrypoint=
safer_port=
safer_inf=
safer_runtime_cmd="$SAFER_RT_CMD"
safer_runtime_args="$SAFER_RT_ARGS"
safer_inf_cmd="${SAFER_PERSIST_CMD:-sleep inf}"
safer_inf_stop_cmd="${SAFER_PERSIST_STOP_CMD:---safer-stop}"

while getopts vhe:p:k:d:R:X:K:S: opt
do
	case $opt in
		e) safer_entrypoint=$OPTARG ;;
		p) safer_port=$OPTARG ;;
		k) safer_inf=$OPTARG ;;
		d) safer_dir=$OPTARG ;;
		R) safer_runtime_cmd=$OPTARG ;;
		X) safer_runtime_args=$OPTARG ;;
		K) safer_inf_cmd=$OPTARG ;;
		S) safer_inf_stop_cmd=$OPTARG ;;
		*) ;;
	esac
done

shift $((OPTIND - 1))

[ -z "$safer_cmd" ] && safer_cmd="$1"
[ -z "$safer_image" ] && safer_image="$2"

if [ -z "$safer_cmd" ] || [ -z "$safer_image" ]; then
	echo "$safer_usage"
	exit
fi

shift 2

# Section 2: Preprocessing of variables

if [ -n "$safer_port" ]; then
	case "$safer_port" in
		*:*) safer_port_map="$safer_port" ;;
		*) safer_port_map="$safer_port:$safer_port" ;;
	esac
fi

if [ -z "$safer_runtime_cmd" ]; then
	if command -v podman >/dev/null 2>&1; then
		safer_runtime_cmd=podman
	elif command -v docker >/dev/null 2>&1; then
		safer_runtime_cmd=docker
	fi
fi

if [ -z "$safer_runtime_args" ] && [ "$safer_runtime_cmd" = "docker" ]; then
	safer_runtime_args='--user "$(id -u):$(id -g)"'
fi

if [ -n "$safer_inf" ] && [ -z "$safer_entrypoint" ]; then
	safer_entrypoint=$(
		$safer_runtime_cmd image inspect \
		--format '{{.Config.Entrypoint}}' \
		"$safer_image"
	)
	safer_entrypoint="$(echo "$safer_entrypoint" | sed 's/^.//')"
	safer_entrypoint="$(echo "$safer_entrypoint" | sed 's/.$//')"
	safer_entrypoint="$(echo "$safer_entrypoint" | sed 's/ /" "/g')"
fi

# Section 3: Writing the script

script_dest="$safer_dir/$safer_cmd"
script_file=$(mktemp)
cwd=$(pwd)
if [ -n "$safer_inf" ]; then
	pad='\t'
fi

{
	printf '#!/bin/sh\n'

	if [ -n "$safer_inf" ]; then
		printf 'if [ "$*" = "%s" ]; then\n' "$safer_inf_stop_cmd"
		printf '\t%s kill %s\n' "$safer_runtime_cmd" "$safer_inf"
		printf '\texit\n'
		printf 'fi\n'
		printf 'if ! %s container inspect %s >/dev/null 2>&1; then\n' "$safer_runtime_cmd" "$safer_inf"
	fi

	if [ -n "$safer_inf" ]; then
		printf '\t%s run --rm \\\n' "$safer_runtime_cmd"
	else
		printf '%s run --rm -ti \\\n' "$safer_runtime_cmd"
	fi

	if [ -n "$safer_runtime_args" ]; then
		printf '%b\t%s \\\n' "$pad" "$safer_runtime_args"
	fi

	if [ -n "$safer_inf" ]; then
		printf '\t\t--entrypoint '\'''\'' \\\n'
	elif [ -n "$safer_entrypoint" ]; then
		printf '\t--entrypoint '\''%s'\'' \\\n' "$safer_entrypoint"
	fi

	if [ -n "$safer_port_map" ]; then
		printf '%b\t-p "%s" \\\n' "$pad" "$safer_port_map"
	fi

	printf '%b\t-v "%s":"%s" \\\n' "$pad" "$cwd" "$cwd"
	printf '%b\t-w "%s"' "$pad" "$cwd"

	for arg in "$@"; do
		printf ' \\\n%b\t-v "%s":"%s"' "$pad" "$arg" "$arg"
	done

	if [ -n "$safer_inf" ]; then
		printf ' \\\n\t\t-d --name "%s" \\\n' "$safer_inf"
	else
		printf ' \\\n'
	fi

	if [ -n "$safer_inf" ]; then
		printf '\t\t%s %s\n' "$safer_image" "$safer_inf_cmd"
	else
		printf '\t%s "$@"\n' "$safer_image"
	fi

	if [ -n "$safer_inf" ]; then
		printf 'fi\n'
			printf '%s exec -ti \\\n' "$safer_runtime_cmd"
		if [ -n "$safer_runtime_args" ]; then
			printf '\t%s \\\n' "$safer_runtime_args"
		fi
		printf '\t-w "%s" \\\n' "$cwd"
		printf '\t%s "%s" "$@"\n' "$safer_inf" "$safer_entrypoint"
	fi

} > "$script_file"

install -D "$script_file" "$script_dest"
rm -f "$script_file"
