#!/bin/sh

set -e

rm -rf tests/outputs
mkdir -p tests/outputs

# PATH definition
test "PATH=\".safer:\$PATH\"" = "$(./safer)"

# PATH definition with -d
test "PATH=\"tests:\$PATH\"" = "$(./safer -d tests)"

export SAFER_DIR=tests/outputs

# PATH definition with env var
test "PATH=\"tests/outputs:\$PATH\"" = "$(./safer)"

if command -v podman >/dev/null 2>&1; then
	test_runtime=podman
elif command -v docker >/dev/null 2>&1; then
	test_runtime=docker
fi

# ---- TEST CASE ----
[ "$1" = "verbose" ] && echo "Illegal option..."
if out=$(./safer -Z 2> /dev/null); then
	exit 1
fi

# ---- TEST CASE ----
[ "$1" = "verbose" ] && echo "Invalid call not detected by optargs..."
if out=$(./safer only_one_arg); then
	exit 1
fi

# ---- TEST CASE ----
[ "$1" = "verbose" ] && echo "Basic generation..."
./safer basic a_tool_image:latest
sed -i 's|'"$(pwd)"'|CWD|g' tests/outputs/basic
[ "$test_runtime" = "docker" ] && sed -i 's|docker|podman|g' tests/outputs/basic
diff tests/refs/basic tests/outputs/basic

# ---- TEST CASE ----
[ "$1" = "verbose" ] && echo "Target other dir and use underscores..."
./safer -d tests/outputs/alt dest a_tool_image:latest
test -e "tests/outputs/alt/dest"

# ---- TEST CASE ----
[ "$1" = "verbose" ] && echo "Don't replace existing scripts..."
if out=$(./safer basic same_tool_image:latest); then
	exit 1
fi
test "$out" = "tests/outputs/basic already exists."

# ---- TEST CASE ----
[ "$1" = "verbose" ] && echo "Generation with port..."
./safer -p 10443 port a_tool_image:latest
sed -i 's|'"$(pwd)"'|CWD|g' tests/outputs/port
[ "$test_runtime" = "docker" ] && sed -i 's|docker|podman|g' tests/outputs/port
diff tests/refs/port tests/outputs/port

# ---- TEST CASE ----
[ "$1" = "verbose" ] && echo "Extra volumes..."
./safer volumes a_tool_image:latest /vol/1 /vol/2
sed -i 's|'"$(pwd)"'|CWD|g' tests/outputs/volumes
[ "$test_runtime" = "docker" ] && sed -i 's|docker|podman|g' tests/outputs/volumes
diff tests/refs/volumes tests/outputs/volumes

# ---- TEST CASE ----
[ "$1" = "verbose" ] && echo "Custom entrypoint..."
./safer -e /bin/other_bin entrypoint a_tool_image:latest
sed -i 's|'"$(pwd)"'|CWD|g' tests/outputs/entrypoint
[ "$test_runtime" = "docker" ] && sed -i 's|docker|podman|g' tests/outputs/entrypoint
diff tests/refs/entrypoint tests/outputs/entrypoint

# ---- TEST CASE ----
[ "$1" = "verbose" ] && echo "Skip pseudo-tty..."
./safer -s skip-tty a_tool_image:latest
sed -i 's|'"$(pwd)"'|CWD|g' tests/outputs/skip-tty
[ "$test_runtime" = "docker" ] && sed -i 's|docker|podman|g' tests/outputs/skip-tty
diff tests/refs/skip-tty tests/outputs/skip-tty

# Persistent containers
if [ -n "$test_runtime" ]; then
	if cd tests/image; then
		$test_runtime build -f Containerfile.no-entrypoint -t safer-test-image-no-entrypoint . > /dev/null
		$test_runtime build -f Containerfile.bin -t safer-test-image-bin . > /dev/null
		$test_runtime build -f Containerfile.sh -t safer-test-image-sh . > /dev/null
		cd - > /dev/null
	fi

	# ---- TEST CASE ----
	[ "$1" = "verbose" ] && echo "Persistent..."
	./safer -k persistent safer-test-image-no-entrypoint
	sed -i 's|'"$(pwd)"'|CWD|g' tests/outputs/persistent
	[ "$test_runtime" = "docker" ] && sed -i 's|docker|podman|g' tests/outputs/persistent
	diff tests/refs/persistent tests/outputs/persistent

	# ---- TEST CASE ----
	[ "$1" = "verbose" ] && echo "Persistent and named..."
	./safer -k -n safer-test-container-named persistent-named safer-test-image-no-entrypoint
	sed -i 's|'"$(pwd)"'|CWD|g' tests/outputs/persistent-named
	[ "$test_runtime" = "docker" ] && sed -i 's|docker|podman|g' tests/outputs/persistent-named
	diff tests/refs/persistent-named tests/outputs/persistent-named

	# ---- TEST CASE ----
	[ "$1" = "verbose" ] && echo "Persistent and simple entrypoint..."
	./safer -n safer-test-container-bin persistent-bin safer-test-image-bin
	sed -i 's|'"$(pwd)"'|CWD|g' tests/outputs/persistent-bin
	[ "$test_runtime" = "docker" ] && sed -i 's|docker|podman|g' tests/outputs/persistent-bin
	diff tests/refs/persistent-bin tests/outputs/persistent-bin

	# ---- TEST CASE ----
	[ "$1" = "verbose" ] && echo "Persistent and sh entrypoint..."
	./safer -n safer-test-container-sh persistent-sh safer-test-image-sh
	sed -i 's|'"$(pwd)"'|CWD|g' tests/outputs/persistent-sh
	[ "$test_runtime" = "docker" ] && sed -i 's|docker|podman|g' tests/outputs/persistent-sh
	diff tests/refs/persistent-sh tests/outputs/persistent-sh

	# ---- TEST CASE ----
	[ "$1" = "verbose" ] && echo "Persistent and sh entrypoint plus most of the flags..."
	./safer -p 10443 -e /bin/other_bin -n safer-test-container-complex -s persistent-complex safer-test-image-sh /vol/1 /vol/2
	sed -i 's|'"$(pwd)"'|CWD|g' tests/outputs/persistent-complex
	[ "$test_runtime" = "docker" ] && sed -i 's|docker|podman|g' tests/outputs/persistent-complex
	diff tests/refs/persistent-complex tests/outputs/persistent-complex

	$test_runtime rmi safer-test-image-no-entrypoint > /dev/null
	$test_runtime rmi safer-test-image-bin > /dev/null
	$test_runtime rmi safer-test-image-sh > /dev/null
fi

export SAFER_LIB_PATH=tests/lib

# ---- TEST CASE ----
[ "$1" = "verbose" ] && echo "Library tool..."
./safer -l lib_tool
sed -i 's|'"$(pwd)"'|CWD|g' tests/outputs/lib_tool
[ "$test_runtime" = "docker" ] && sed -i 's|docker|podman|g' tests/outputs/lib_tool
diff tests/refs/lib_tool tests/outputs/lib_tool

# ---- TEST CASE ----
[ "$1" = "verbose" ] && echo "Missing library tool..."
if out=$(./safer -l not_a_lib_tool); then
	exit 1
fi
test "$out" = "not_a_lib_tool tool not found in library."

# ---- TEST CASE ----
[ "$1" = "verbose" ] && echo "Library tool with extra volumes /vol/1 /vol/2..."
./safer -l lib_tool_volumes /vol/1 /vol/2
sed -i 's|'"$(pwd)"'|CWD|g' tests/outputs/lib_tool_volumes
[ "$test_runtime" = "docker" ] && sed -i 's|docker|podman|g' tests/outputs/lib_tool_volumes
diff tests/refs/lib_tool_volumes tests/outputs/lib_tool_volumes

# ---- TEST CASE ----
[ "$1" = "verbose" ] && echo "Library image..."
expected=$(mktemp)
actual=$(mktemp)
cat > "$expected" <<EOF
Build script was installed. Review and build with:
cat "tests/outputs/build/lib_tool"
(podman|docker) build -t "safer-lib_tool:latest" -f "lib_tool" "tests/outputs/build"
EOF
./safer -i lib_tool > "$actual"
[ "$test_runtime" = "docker" ] && sed -i 's|docker|podman|g' tests/outputs/build/lib_tool
diff tests/lib/images/lib_tool tests/outputs/build/lib_tool
diff "$expected" "$actual"
rm "$expected"
rm "$actual"

# ---- TEST CASE ----
[ "$1" = "verbose" ] && echo "Missing library image..."
if out=$(./safer -i not_a_lib_image); then
	exit 1
fi
test "$out" = "not_a_lib_image image not found in library."

# ---- TEST CASE ----
[ "$1" = "verbose" ] && echo "Don't replace build file from library..."
if out=$(./safer -i lib_tool); then
	exit 1
fi
test "$out" = "tests/outputs/build/lib_tool already exists."

# ---- TEST CASE ----
[ "$1" = "verbose" ] && echo "Docker override..."
SAFER_RT_CMD="docker" ./safer docker_rt a_tool_image:latest
sed -i 's|'"$(pwd)"'|CWD|g' tests/outputs/docker_rt
[ "$test_runtime" = "docker" ] && sed -i 's|docker|podman|g' tests/outputs/docker_rt
diff tests/refs/docker_rt tests/outputs/docker_rt

# ---- TEST CASE ----
[ "$1" = "verbose" ] && echo "Docker override (sudo + no args)..."
SAFER_RT_CMD="sudo docker" SAFER_RT_ARGS="" ./safer docker_rt_sudo_no_args a_tool_image:latest
sed -i 's|'"$(pwd)"'|CWD|g' tests/outputs/docker_rt_sudo_no_args
[ "$test_runtime" = "docker" ] && sed -i 's|docker|podman|g' tests/outputs/docker_rt_sudo_no_args
diff tests/refs/docker_rt_sudo_no_args tests/outputs/docker_rt_sudo_no_args
