.TH SAFER 1
.SH NAME
safer \- run project tools in containers using proxy scripts
.SH SYNOPSIS
.B safer
.br
.B safer
[OPTIONS] <CMD> <IMAGE> [DIR...]
.SH DESCRIPTION
.B safer
creates a CMD script to run a dev tool using a container IMAGE.
.P
The current directory, and any extra DIR specified, are mounted in the
container using the same paths as the mount points.
.P
The commands are created in the .safer directory. You can add this
directory to your PATH or you can run
.B safer
without any option to run a SHELL with a modified PATH.
.SH OPTIONS
.TP
.BR \-e
Tool entrypoint in the image.
.TP
.BR \-d
Directory for the scripts. Default: .safer .
.TP
.BR \-R
Runtime cli command. Override podman/docker detection.
.TP
.BR \-X
Runtime extra args.
.br
Docker default: '--user "$(id -u):$(id -g)"'.
.TP
.BR \-v ", " \-\-version
Display the current version.
.TP
.BR \-h ", " \-\-help
Display usage and exit.
.SH ENVIRONMENT
.TP
.B SAFER_DIR
Directory for the scripts. Default: .safer .
.TP
.B SAFER_RT_CMD
Runtime cli command. Override podman/docker detection.
.TP
.B SAFER_RT_ARGS
Runtime extra args.
.br
Docker default: '--user "$(id -u):$(id -g)"'.
.TP
.B SHELL
Shell used to run the sub-shell when no args are specified.
.SH FILES
.TP
.BR /etc/safer ", "~/.saferrc ", ".saferrc
These files are sourced by safer.
