#!/bin/sh

set -e

rm -f tests/outputs/*

# Basic generation
./safer -d tests/outputs 00-basic-script a_tool_image:latest
sed -i 's|'"$(pwd)"'|CWD|g' tests/outputs/00-basic-script
diff tests/refs/00-basic-script tests/outputs/00-basic-script

# SAFER_DIR override
SAFER_DIR=tests/outputs ./safer 00_01_basic_script a_tool_image:latest
sed -i 's|'"$(pwd)"'|CWD|g' tests/outputs/00_01_basic_script
diff tests/refs/00-basic-script tests/outputs/00_01_basic_script

# Don't replace existing scripts
if ./safer -d tests/outputs 00-basic-script same_tool_image:latest > /dev/null; then
	exit 1
fi
diff tests/refs/00-basic-script tests/outputs/00-basic-script

# Generation with port
./safer -d tests/outputs -p 10443 01-port a_tool_image:latest
sed -i 's|'"$(pwd)"'|CWD|g' tests/outputs/01-port
diff tests/refs/01-port tests/outputs/01-port
