#!/bin/sh

version=0.0-dev

usage="Usage:
$0 [[OPTIONS] [<cmd> <image> [dir...]]]

Arguments:
 cmd         Name of the tool executable.
 image       Image where the tool executable resides.
 dir         Extra directories to mount in the container.

For the full list of Options and Environment Vars, see the man page.

Options:
 -e cmd      Tool entrypoint in the image.
 -p n[:n]    Port to expose.
 -k          Run the tool in a persistent container.
 -n name     Use this name to persist the container (implies -k).
 -f          Force script replacement.
 -s          Skip container pseudo-tty allocation.
 -l tool     Get the tool definition from the library.
 -i tool     Install a Containerfile from the library.
 -v          Display the current version.
 -h          Display usage and exit.

Environment Vars:
 SAFER_DIR      Directory for the scripts. Default .safer .

Config files: /etc/safer, ~/.saferrc, .saferrc"

# Section 1: Init safer and read args/env

[ -e "/etc/safer" ] && . "/etc/safer"
[ -e "$HOME/.saferrc" ] && . "$HOME/.saferrc"
[ -e ".saferrc" ] && . ".saferrc"

script_dir=${SAFER_DIR:-.safer}
lib_path=${SAFER_LIB_PATH:-~/.local/share/safer:/usr/share/safer:/usr/local/share/safer}
persist_cmd="${SAFER_PERSIST_CMD:-sleep inf}"
persist_stop_cmd="${SAFER_PERSIST_STOP_CMD:---safer-stop}"

while getopts e:p:kn:d:R:X:K:S:fsl:i:vh opt
do
	case $opt in
		e) entrypoint=$OPTARG ;;
		p) port=$OPTARG ;;
		k) persist=1 ;;
		n) container_name=$OPTARG; persist=1 ;;
		d) script_dir=$OPTARG ;;
		R) runtime_cmd=$OPTARG ;;
		X) runtime_args=$OPTARG ;;
		K) persist_cmd=$OPTARG; persist=1 ;;
		S) persist_stop_cmd=$OPTARG; persist=1 ;;
		f) force=1 ;;
		s) skip_tty=1 ;;
		l) lib_tool=$OPTARG ;;
		i) lib_image=$OPTARG ;;
		v) echo $version && exit ;;
		h) echo "$usage" && exit ;;
		\?) echo "$usage" && exit 1 ;;
		*) ;;
	esac
done

shift $((OPTIND - 1))

# Section 2: Library commands

find_item_in_lib() {
	oldifs=$IFS
	IFS=:
	for location in $lib_path; do
		if [ -e "$location/$1/$2" ]; then
			echo "$location/$1/$2"
			break
		fi
	done
	IFS=$oldifs
}

if [ "${lib_tool+x}" ]; then
	found=$(find_item_in_lib tools "$lib_tool")
	if [ -n "$found" ]; then
		sh "$found" "$@"
	else
		echo "$lib_tool tool not found in library."
		exit 1
	fi
	exit
fi

if [ "${lib_image+x}" ] && [ $# -eq 0 ]; then
	found=$(find_item_in_lib images "$lib_image")
	if [ -n "$found" ]; then
		if [ -e "$script_dir/build/$lib_image" ]; then
			echo "$script_dir/build/$lib_image already exists."
			exit 1
		else
			mkdir -p "$script_dir/build"
			cp "$found" "$script_dir/build/$lib_image"
			echo "Build script was installed. Review and build with:"
			printf 'cat "%s"\n' "$script_dir/build/$lib_image"
			printf '(podman|docker) build -t "safer-%s:latest" -f "%s" "%s"\n' "$lib_image" "$lib_image" "$script_dir/build"
		fi
	else
		echo "$lib_image image not found in library."
		exit 1
	fi
	exit
fi

# Section 3: Non-library execution, PATH definition and bad args exit

if [ $# -gt 1 ]; then
	tool="$1"
	image="$2"
	shift 2
elif [ $# -eq 0 ]; then
	printf 'PATH="%s:$PATH"\n' "$script_dir"
	exit
else
	echo "$usage"
	exit 1
fi

# Section 4: Simple pre-processing of vars

script_dest="$script_dir/$tool"
if [ -e "$script_dest" ] && [ -z "$force" ]; then
	echo "$script_dest already exists."
	exit 1
fi

if [ -n "$port" ]; then
	case "$port" in
		*:*) port_map="$port" ;;
		*) port_map="$port:$port" ;;
	esac
fi

if [ "${persist+x}" ] && [ -z "$container_name" ]; then
	clean_cmd="$(echo "${PWD##*/}" | tr -cd '[:alnum:]')"
	container_name="$tool-$clean_cmd"
fi

if [ -z "${runtime_cmd:=$SAFER_RT_CMD}" ]; then
	if command -v podman >/dev/null 2>&1; then
		runtime_cmd=podman
	elif command -v docker >/dev/null 2>&1; then
		runtime_cmd=docker
	else
		echo "Cannot detect a container runtime. See man page for more info."
		exit 1
	fi
fi

if [ ! "${runtime_args+x}" ]; then
	if [ "${SAFER_RT_ARGS+x}"  ]; then
		runtime_args=$SAFER_RT_ARGS
	else
		if [ "$runtime_cmd" = "docker" ] || [ "$runtime_cmd" = "sudo docker" ]; then
			runtime_args='--user "$(id -u):$(id -g)"'
		fi
	fi
fi

# Section 5: Preprocessing of the original entrypoint parts

if [ -n "$container_name" ]; then
	pad='\t'  # indent the original run lines on persistent scripts
fi

# Freeing $@
extra_volumes=
for arg in "$@"; do
	next_volume=$(printf ' \\\n%b\t-v "%s":"%s"' "$pad" "$arg" "$arg")
	extra_volumes=$extra_volumes$next_volume
done

# Capture original image entrypoint and args
if [ -n "$container_name" ] && [ -z "$entrypoint" ]; then
	set -f
	oldifs=$IFS
	IFS='
'
	# shellcheck disable=SC2046
	set -- $(
		$runtime_cmd image inspect \
		--format '{{range .Config.Entrypoint}}{{println .}}{{end}}' \
		"$image"
	)
	IFS=$oldifs

	if [ $# -gt 0 ]; then
		og_entrypoint=$1
		shift

		for arg in "$@"; do
			og_exec_args=$og_exec_args$(
				printf "'%s' " "$(printf "%s" "$arg" | sed "s/'/'\\\\''/g")"
			)
		done
		[ -n "$og_exec_args" ] && og_exec_args=${og_exec_args%?}
	fi
fi

# Section 6: Writing the script

script_file=$(mktemp)
cwd=$(pwd -P)

interactive_flag=-ti
[ "${skip_tty+x}" ] && interactive_flag=-i

{
	printf '#!/bin/sh\n'

	printf 'project_dir="%s"\n' "$cwd"
	printf 'case "$(pwd -P)/" in\n'
	printf '\t"$project_dir/"*) ;;\n'
	printf '\t*) echo "safer: $0: outside project dir" 2>&1; exit 1 ;;\n'
	printf 'esac\n'

	if [ -n "$container_name" ]; then
		printf 'if [ "$*" = "%s" ]; then\n' "$persist_stop_cmd"
		printf '\t%s kill %s\n' "$runtime_cmd" "$container_name"
		printf '\texit\n'
		printf 'fi\n'
		printf 'if ! %s container inspect %s >/dev/null 2>&1; then\n' "$runtime_cmd" "$container_name"
	fi

	if [ -n "$container_name" ]; then
		printf '\t%s run --rm \\\n' "$runtime_cmd"
	else
		printf '%s run --rm %s \\\n' "$runtime_cmd" "$interactive_flag"
	fi

	if [ -n "$runtime_args" ]; then
		printf '%b\t%s \\\n' "$pad" "$runtime_args"
	fi

	if [ -n "$container_name" ]; then
		printf '\t\t--entrypoint '\'''\'' \\\n'
	elif [ -n "$entrypoint" ]; then
		printf '\t--entrypoint '\''%s'\'' \\\n' "$entrypoint"
	fi

	if [ -n "$port_map" ]; then
		printf '%b\t-p "%s" \\\n' "$pad" "$port_map"
	fi

	printf '%b\t-v "%s":"%s" \\\n' "$pad" "$cwd" "$cwd"

	if [ -n "$container_name" ]; then
		printf '\t\t-w "$project_dir"'
	else
		printf '\t-w "$(pwd -P)"'
	fi

	printf '%s' "$extra_volumes"

	if [ -n "$container_name" ]; then
		printf ' \\\n\t\t-d --name "%s" \\\n' "$container_name"
	else
		printf ' \\\n'
	fi

	if [ -n "$container_name" ]; then
		printf '\t\t%s %s\n' "$image" "$persist_cmd"
	else
		printf '\t%s "$@"\n' "$image"
	fi

	if [ -n "$container_name" ]; then
		printf 'fi\n'
		printf '%s exec %s \\\n' "$runtime_cmd" "$interactive_flag"
		if [ -n "$runtime_args" ]; then
			printf '\t%s \\\n' "$runtime_args"
		fi
		printf '\t-w "$(pwd -P)" \\\n'
		if [ -n "$entrypoint" ]; then
			printf '\t%s '\''%s'\'' "$@"\n' "$container_name" "$entrypoint"
		else
			if [ -z "$og_entrypoint" ]; then
				printf '\t%s "$@"\n' "$container_name"
			elif [ -z "$og_exec_args" ]; then
				printf '\t%s '\''%s'\'' "$@"\n' "$container_name" "$og_entrypoint"
			else
				printf '\t%s '\''%s'\'' %s "$@"\n' "$container_name" "$og_entrypoint" "$og_exec_args"
			fi
		fi
	fi

} > "$script_file"

install -D "$script_file" "$script_dest"
rm -f "$script_file"
