#!/bin/sh

# TODO: persistence
# TODO: auto-image from cmd name
# TODO: safer-images if not image

safer_ver=0.0-dev

safer_usage="Usage:
$0 [[OPTIONS] [<cmd> <image> [dir...]]]

Arguments:
 cmd         Name of the tool executable.
 image       Image where the tool executable resides.
 dir         Extra directories to mount in the container.

For the full list of Options and Environment Vars, see the man page.

Options:
 -e             Tool entrypoint in the image.
 -d             Directory for the scripts. Default: .safer .
 -v, --version  Display the current version.
 -h, --help     Display usage and exit.

Environment Vars:
 SAFER_DIR      Directory for the scripts. Default .safer .

Config files: /etc/safer, ~/.saferrc, .saferrc"

[ -e "/etc/safer" ] && . "/etc/safer"
[ -e "$HOME/.saferrc" ] && . "$HOME/.saferrc"
[ -e ".saferrc" ] && . ".saferrc"

safer_dir=${SAFER_DIR:-.safer}

if [ "$#" -eq 0 ]; then
	case ":$PATH:" in
		*":$safer_dir:"*) exit ;;
		*) PATH="$safer_dir:$PATH" ${SHELL:-sh} && exit ;;
	esac
fi

case " $@ " in
	*" -v "*|*" --version "*) echo $safer_ver && exit ;;
	*" -h "*|*" --help "*) echo "$safer_usage" && exit ;;
esac

safer_cmd=
safer_image=
safer_entryporint=
safer_runtime_cmd="$SAFER_RT_CMD"
safer_runtime_args="$SAFER_RT_ARGS"

while getopts vhe:d:R:X: opt
do
	case $opt in
		e) safer_entryporint=$OPTARG ;;
		d) safer_dir=$OPTARG ;;
		R) safer_runtime_cmd=$OPTARG ;;
		X) safer_runtime_args=$OPTARG ;;
		*) ;;
	esac
done

shift $((OPTIND - 1))

[ -z "$safer_cmd" ] && safer_cmd="$1"
[ -z "$safer_image" ] && safer_image="$2"

if [ -z "$safer_cmd" ] || [ -z "$safer_image" ]; then
	echo "$safer_usage"
	exit
fi

shift 2

if [ -z "$safer_runtime_cmd" ]; then
	if command -v podman >/dev/null 2>&1; then
		safer_runtime_cmd=podman
	elif command -v docker >/dev/null 2>&1; then
		safer_runtime_cmd=docker
	fi
fi

if [ -z "$safer_runtime_args" ] && [ "$safer_runtime_cmd" = "docker" ]; then
	safer_runtime_args='--user "$(id -u):$(id -g)"'
fi

script_dest="$safer_dir/$safer_cmd"
script_file=$(mktemp)
cwd=$(pwd)

{
	printf '#!/bin/sh\n'

	printf '%s run --rm -i \\\n' "$safer_runtime_cmd"

	if [ -n "$safer_runtime_args" ]; then
		printf '\t%s \\\n' "$safer_runtime_args"
	fi

	if [ -n "$safer_entryporint" ]; then
		printf '\t--entrypoint "%s" \\\n' "$safer_entryporint"
	fi

	printf '\t-v "%s":"%s" \\\n' "$cwd" "$cwd"
	printf '\t-w "%s"' "$cwd"

	for arg in "$@"; do
		printf ' \\\n\t-v "%s":"%s"' "$arg" "$arg"
	done

	printf ' \\\n\t%s "$@"\n' "$safer_image"

} > "$script_file"

install -D "$script_file" "$script_dest"
rm -f "$script_file"
