#!/bin/sh
project_dir="CWD"
case "$(pwd -P)/" in
	"$project_dir/"*) ;;
	*) echo "safer: $0: outside project dir" 2>&1; exit 1 ;;
esac
docker run --rm -ti \
	--user "$(id -u):$(id -g)" \
	-v "CWD":"CWD" \
	-w "$(pwd -P)" \
	a_tool_image:latest "$@"
