#!/bin/sh
project_dir="CWD"
case "$(pwd -P)/" in
	"$project_dir/"*) ;;
	*) echo "safer: $0: outside project dir" >&2; exit 1 ;;
esac
if [ "$*" = "--other-safer-stop" ]; then
	podman kill persistent-arg-safer
	exit
fi
if ! podman container inspect persistent-arg-safer >/dev/null 2>&1; then
	podman run --rm \
		--entrypoint '' \
		-v "CWD":"CWD" \
		-w "$project_dir" \
		-d --name "persistent-arg-safer" \
		safer-test-image-no-entrypoint sleep inf
fi
podman exec -ti \
	-w "$(pwd -P)" \
	persistent-arg-safer "$@"
