#!/bin/sh
project_dir="CWD"
case "$(pwd -P)/" in
	"$project_dir/"*) ;;
	*) echo "safer: $0: outside project dir" 2>&1; exit 1 ;;
esac
if [ "$*" = "--safer-stop" ]; then
	podman kill safer-test-container-complex
	exit
fi
if ! podman container inspect safer-test-container-complex >/dev/null 2>&1; then
	podman run --rm \
		--entrypoint '' \
		-p "10443:10443" \
		-v "CWD":"CWD" \
		-w "$project_dir" \
		-v "/vol/1":"/vol/1" \
		-v "/vol/2":"/vol/2" \
		-d --name "safer-test-container-complex" \
		safer-test-image-sh sleep inf
fi
podman exec -i \
	-w "$(pwd -P)" \
	safer-test-container-complex '/bin/other_bin' "$@"
