#!/bin/sh
project_dir="CWD"
case "$(pwd -P)/" in
	"$project_dir/"*) ;;
	*) echo "safer: $0: outside project dir" >&2; exit 1 ;;
esac
interactive_flags=-i
if [ -t 1 ]; then
	interactive_flags=-it
fi
if [ "$*" = "--safer-stop" ]; then
	podman kill safer-test-container-sh
	exit
fi
if ! podman container inspect safer-test-container-sh >/dev/null 2>&1; then
	podman run --rm \
		--entrypoint '' \
		-v "CWD":"CWD" \
		-w "$project_dir" \
		-d --name "safer-test-container-sh" \
		safer-test-image-sh sleep inf
fi
podman exec $interactive_flags \
	-w "$(pwd -P)" \
	safer-test-container-sh '/bin/sh' '-c' '"sh", "entrypoint"' "$@"
