#!/bin/sh
project_dir="CWD"
case "$(pwd -P)/" in
	"$project_dir/"*) ;;
	*) echo "safer: $0: outside project dir" >&2; exit 1 ;;
esac
interactive_flags=-i
if [ -t 1 ]; then
	interactive_flags=-it
fi
if [ "$*" = "--safer-stop" ]; then
	docker kill safer-test-container-bin
	exit
fi
if ! docker container inspect safer-test-container-bin >/dev/null 2>&1; then
	docker run --rm \
		--entrypoint '' \
		-v "CWD":"CWD" \
		-w "$project_dir" \
		-d --name "safer-test-container-bin" \
		safer-test-image-bin sleep inf
fi
docker exec $interactive_flags \
	-w "$(pwd -P)" \
	safer-test-container-bin '/usr/local/some_bin' "$@"
