#!/bin/sh
project_dir="CWD"
case "$(pwd -P)/" in
	"$project_dir/"*) ;;
	*) echo "safer: $0: outside project dir" >&2; exit 1 ;;
esac
interactive_flags=-i
if [ -t 1 ]; then
	interactive_flags=-it
fi
if [ "$*" = "--other-safer-stop" ]; then
	docker kill persistent-arg-safer
	exit
fi
if ! docker container inspect persistent-arg-safer >/dev/null 2>&1; then
	docker run --rm \
		--entrypoint '' \
		-v "CWD":"CWD" \
		-w "$project_dir" \
		-d --name "persistent-arg-safer" \
		safer-test-image-no-entrypoint sleep inf
fi
docker exec $interactive_flags \
	-w "$(pwd -P)" \
	persistent-arg-safer "$@"
