#!/bin/sh
project_dir="CWD"
case "$(pwd -P)/" in
	"$project_dir/"*) ;;
	*) echo "safer: $0: outside project dir" >&2; exit 1 ;;
esac
interactive_flags=-i
if [ -t 1 ]; then
	interactive_flags=-it
fi
if [ "$*" = "--safer-stop" ]; then
	podman kill persistent-safer
	exit
fi
if ! podman container inspect persistent-safer >/dev/null 2>&1; then
	podman run --rm \
		--entrypoint '' \
		-v "CWD":"CWD" \
		-w "$project_dir" \
		-d --name "persistent-safer" \
		safer-test-image-no-entrypoint sleep inf
fi
podman exec $interactive_flags \
	-w "$(pwd -P)" \
	persistent-safer "$@"
